build:
  image: ctornau/latex
  stage: build
  artifacts:
    paths:
      - main.pdf
  script:
    # This is needed for colored code blocks. If you dont need
    # them, you can remove this section
    - apt-get -y update
    - apt-get -y install python3-pip
    - pip3 install pygments
    # section end
    - latexmk -shell-escape -pdf main.tex

# This will host the PDF w/ Gitlab Pages
pages:
  image: alpine:latest
  stage: deploy
  dependencies:
    - build
  script:
    # Feel free to change the mv target to something else. You will need to update the index.html though
    # Everything inside public will be hosted by Pages
    - mv main.pdf public/main.pdf

  artifacts:
    paths:
      - public