image: texlive/texlive:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

compile-pdfs:
  stage: build
  script:
    - ./compile-pdfs.sh
  after_script:
    - mv compiled/*.pdf . || true
    - mv compiled/*.log . || true
  artifacts:
    paths:
      - ./*.pdf
      - ./*.log
    when: always
    expire_in: 2 weeks

